language: cpp
notifications:
  email:
    - kuemmerl@informatik.uni-freiburg.de
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-opengl-dev libqglviewer-qt4-dev libeigen3-dev libsuitesparse-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
